general {
    hide_cursor = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3

    inner_color = rgb(202020)
    outer_color = rgb(505050)
    check_color = rgb(00ff99)
    fail_color = rgb(ff6633)

    font_color = rgb(aaaaaa)
    fade_on_empty = false
    rounding = 15

    font_family = JetBrainsMono Nerd Font
    placeholder_text = Password please :3
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_text_format = *

    halign = center
    valign = center
}
